// Generated by CoffeeScript 1.5.0
(function() {
  var getInputBoxes;

  getInputBoxes = "inputBoxes = document.querySelectorAll('input[id^=AnSwEr]')";

  chrome.tabs.onUpdated.addListener(function(tabId, changeInfo, tab) {
    if (changeInfo.status === 'complete') {
      return chrome.permissions.contains({
        permissions: ['tabs'],
        origins: ["http://*/*", "https://*/*"]
      }, function(permitted) {
        if (permitted) {
          if (tab.url.slice(0, 4) === 'http') {
            return chrome.tabs.executeScript(tabId, {
              code: getInputBoxes
            }, function(result) {
              if (Object.keys(result[0]).length !== 0) {
                chrome.tabs.insertCSS(tabId, {
                  file: "mathscribe/jqmath-0.3.0.css"
                });
                return chrome.tabs.executeScript(tabId, {
                  file: "mathscribe/jquery-1.9.1.min.js"
                }, function() {
                  return chrome.tabs.executeScript(tabId, {
                    file: "mathscribe/jquery-migrate-1.1.1.min.js"
                  }, function() {
                    return chrome.tabs.executeScript(tabId, {
                      file: "mathscribe/jqmath-etc-0.3.0.min.js"
                    }, function() {
                      return chrome.tabs.executeScript(tabId, {
                        file: "equations.js"
                      }, function() {
                        return chrome.tabs.executeScript(tabId, {
                          file: "webwork.js"
                        });
                      });
                    });
                  });
                });
              }
            });
          }
        }
      });
    }
  });

}).call(this);
