//@ sourceMappingURL=eventPage.map
// Generated by CoffeeScript 1.6.1
(function() {
  var loadEquations;

  loadEquations = function(tabId, tab) {
    var getInputBoxes, storeURL;
    storeURL = 'https://chrome.google.com/webstore';
    getInputBoxes = "inputBoxes = document.querySelectorAll('input[id*=AnSwEr]')";
    if (tab.url.slice(0, 4) === 'http' && tab.url.slice(0, storeURL.length) !== storeURL) {
      return chrome.tabs.executeScript(tabId, {
        code: getInputBoxes
      }, function(result) {
        if (Object.keys(result[0]).length !== 0) {
          chrome.tabs.insertCSS(tabId, {
            file: "mathscribe/jqmath-0.3.0.css"
          });
          return chrome.tabs.executeScript(tabId, {
            file: "mathscribe/jquery-1.9.1.min.js"
          }, function() {
            return chrome.tabs.executeScript(tabId, {
              file: "mathscribe/jquery-migrate-1.1.1.min.js"
            }, function() {
              return chrome.tabs.executeScript(tabId, {
                file: "mathscribe/jqmath-etc-0.3.0.min.js"
              }, function() {
                return chrome.tabs.executeScript(tabId, {
                  file: "equations.js"
                }, function() {
                  return chrome.tabs.executeScript(tabId, {
                    file: "webwork.js"
                  });
                });
              });
            });
          });
        }
      });
    }
  };

  chrome.tabs.onUpdated.addListener(function(tabId, changeInfo, tab) {
    if (changeInfo.status === 'complete') {
      return chrome.permissions.contains({
        permissions: ['tabs'],
        origins: ["http://*/*", "https://*/*"]
      }, function(permitted) {
        if (permitted) {
          return loadEquations(tabId, tab);
        }
      });
    }
  });

}).call(this);
