// Generated by CoffeeScript 2.7.0
(function() {
  var createDataTransfer, imageToDataURL, picker;

  createDataTransfer = function(url, name) {
    var data, dt, file, parts, type;
    parts = url.split(',');
    type = parts[0].split(':')[1].split(';')[0];
    data = Uint8Array.from(atob(parts[1]), function(c) {
      return c.charCodeAt(0);
    });
    file = new File([data], name, {
      type: type
    });
    dt = new DataTransfer();
    dt.items.add(file);
    return dt;
  };

  imageToDataURL = function(img, width, height) {
    var canvas, ctx;
    canvas = document.createElement('canvas');
    ctx = canvas.getContext('2d');
    canvas.width = width;
    canvas.height = height;
    ctx.drawImage(img, 0, 0, width, height);
    return canvas.toDataURL();
  };

  picker = Array.from(document.querySelectorAll('[jsaction*=drop]')).pop();

  if (picker) {
    picker.addEventListener('drop', function(e) {
      var img, url;
      e.preventDefault();
      url = e.dataTransfer.getData('text/uri-list');
      if (!url.startsWith('data:image/png;base64,')) {
        return;
      }
      img = document.createElement('img');
      img.onload = function() {
        var dt, input;
        url = imageToDataURL(img, img.width / 2, img.height / 2);
        dt = createDataTransfer(url, 'equation.png');
        input = picker.querySelector('input[type=file]');
        input.files = dt.files;
        return input.dispatchEvent(new Event('change', {
          bubbles: true
        }));
      };
      return img.src = url;
    });
  }

}).call(this);

//# sourceMappingURL=google-picker.js.map
