// Generated by CoffeeScript 2.3.2
(function() {
  var handlePermissions;

  handlePermissions = function(checkbox, permissions) {
    chrome.permissions.contains(permissions, function(result) {
      if (result) {
        return checkbox.checked = true;
      }
    });
    return checkbox.onclick = function() {
      if (checkbox.checked) {
        return chrome.permissions.request(permissions, function(granted) {
          if (!granted) {
            return checkbox.checked = false;
          }
        });
      } else {
        return chrome.permissions.remove(permissions);
      }
    };
  };

  window.onload = function() {
    var enableGoogleForms, enableWebwork, permissions;
    enableWebwork = document.querySelector('#enableWebwork');
    permissions = {
      permissions: ['tabs'],
      origins: ['http://*/*', 'https://*/*']
    };
    handlePermissions(enableWebwork, permissions);
    enableGoogleForms = document.querySelector('#enableGoogleForms');
    permissions = {
      permissions: ['tabs', 'webNavigation'],
      origins: ['http://docs.google.com/*', 'https://docs.google.com/*']
    };
    return handlePermissions(enableGoogleForms, permissions);
  };

}).call(this);

//# sourceMappingURL=options.js.map
