// Generated by CoffeeScript 1.5.0
(function() {

  window.onload = function() {
    var enableWebwork, permissions;
    enableWebwork = document.getElementById('enable-webwork');
    permissions = {
      permissions: ["tabs"],
      origins: ["http://*/*", "https://*/*"]
    };
    chrome.permissions.contains(permissions, function(result) {
      if (result) {
        return enableWebwork.checked = true;
      }
    });
    return enableWebwork.onclick = function() {
      if (enableWebwork.checked) {
        return chrome.permissions.request(permissions);
      } else {
        return chrome.permissions.remove(permissions);
      }
    };
  };

}).call(this);
