// Generated by CoffeeScript 1.3.3
(function() {

  window.onload = function() {
    var equationBox, inputBox, message;
    inputBox = document.getElementById('inputBox');
    equationBox = document.getElementById('equationBox');
    message = equationBox.innerHTML;
    startEquations(inputBox, equationBox, message, true);
    return inputBox.onsearch = function() {
      if (inputBox.value) {
        return chrome.tabs.create({
          url: 'http://www.wolframalpha.com/input/?i=' + encodeURIComponent(inputBox.value)
        });
      } else {
        return equationBox.innerHTML = message;
      }
    };
  };

}).call(this);
