// Generated by CoffeeScript 2.7.0
(function() {
  window.onload = async function() {
    var equation, equationBox, inputBox, items, timeout;
    inputBox = document.getElementById('inputBox');
    equationBox = document.getElementById('equationBox');
    items = (await chrome.storage.sync.get('equation'));
    if (items.equation) {
      inputBox.value = items.equation;
    }
    timeout = null;
    equation = new Equation(inputBox, equationBox, false, function() {
      if (timeout) {
        clearTimeout(timeout);
      }
      return timeout = setTimeout(async function() {
        timeout = null;
        return (await chrome.storage.sync.set({
          equation: inputBox.value
        }));
      }, timeout ? 10 : 0);
    });
    return inputBox.onsearch = async function() {
      var url;
      if (inputBox.value) {
        url = `https://www.wolframalpha.com/input/?i=${encodeURIComponent(inputBox.value)}`;
        return (await chrome.tabs.create({
          url: url
        }));
      }
    };
  };

}).call(this);

//# sourceMappingURL=popup.js.map
