//@ sourceMappingURL=webwork.map
// Generated by CoffeeScript 1.6.1
(function() {
  var equationBox, inputBox, parent, _i, _len;

  for (_i = 0, _len = inputBoxes.length; _i < _len; _i++) {
    inputBox = inputBoxes[_i];
    parent = inputBox.parentNode;
    equationBox = document.createElement('div');
    equationBox.style.display = 'inline-block';
    equationBox.style.padding = '10px';
    parent.insertBefore(equationBox, inputBox);
    parent.insertBefore(document.createElement('br'), inputBox);
    parent.insertBefore(document.createElement('br'), equationBox);
    startEquations(inputBox, equationBox);
  }

}).call(this);
